spring:
  datasource:
    url: jdbc:mysql://210.28.144.91:3306/agent_plaza?useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: Shenhui@123
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl

cas:
  client-server-url: http://210.28.145.186:3001/agent-plaza
  front-end-url: http://210.28.145.186:3001/agent-plaza

logging:
  level:
    com.wxut.agentplaza: INFO
